// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtjejtoufzwsgskcocsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10amVqdG91Znp3c2dza2NvY3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMzE5MTEsImV4cCI6MjA1NDYwNzkxMX0.RDJ_8__vAnSbxQEGI_W6L2iKq_LDuwSTIgdtT_N7ToQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);